basic_app/urls.py
from django.urls import path, re_path
from basic_app import views

# TEMPLATE URLS
app_name = 'basic_app'

urlpatterns = [
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^user_login/$', views.user_login, name='user_login'),
]

users_auth/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    re_path(r'^logout/$', views.user_logout, name='logout'),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    # additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import  UserForm, UserProfileInfoForm

# imports for login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        # grab info from forms
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            # saving user from form
            user = user_form.save()
            # hashing password
            user.set_password(user.password)
            # saving udpated user with hashed password
            user.save()

            # don't save yet (see below)
            profile = profile_form.save(commit=False)
            # sets onetoone relationship
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form =  UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                            {'user_form': user_form,
                             'profile_form': profile_form,
                             'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("SOMEONE TRIED TO LOGIN AND FAILED")
            print(f"Username: {username} and password {password}")
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request, 'basic_app/login.html', {})

templates/basic_app/base.html
<!DOCTYPE html>
{# Load the tag library #}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
            aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggler">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
            </li>

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block body_block %}
    {% endblock %}
</div>

</body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}
    {% block body_block %}

        <div class="jumbotron">
            <h1 class="display-4">Homepage</h1>
        </div>
    {% endblock %}

templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% load bootstrap4 %}

{% block body_block %}

    <div class="jumbotron">
        <h1 class="display-4">Please Login</h1>

        {# Display a form #}
        <form action="{% url 'basic_app:user_login' %}" method="post" class="form-group">
            {% csrf_token %}

            <label for="username">Username: </label>
            <input type="text" class="form-control" name="username" placeholder="Enter Username">

            <label for="password">Password: </label>
            <input type="password" class="form-control" name="password" placeholder="Enter password">

            {% buttons %}
                <button type="submit" class="btn btn-primary" value="Login">Login</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}

{% block body_block %}

    <div class="jumbotron">
        {% if registered %}
            <h1>Thank You for registering!</h1>
        {% else %}
            <h1>Register Here!</h1>
            <p class="lead">Fill out the form:</p>

            {# Display a form #}
            <form enctype="multipart/form-data" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form user_form %}
                {% bootstrap_form profile_form %}

                {% buttons %}
                    <button type="submit" class="btn btn-primary" value="Register">Register</button>
                {% endbuttons %}
            </form>
        {% endif %}
    </div>
{% endblock %}